### ISSUE TITLE
Support for timezone abbreviation (EST, PDT, PST) and AM/PM

### ISSUE THREAD

**Issue by pepie** [Dana-Ferguson/time_machine#14]
Hello,
How do I get the abbreviated timezone name, and the am/pm designation?
`Dec 23, 2018 @ 08:00 AM PST`

Example:
Given a start date as
DateTime start = DateTime(...);
DateTimeZone losAngeles = ...;

Instance i = Instance.dateTime(start);
print(instance.inZone(losAngeles).toString('MMM dd, yyyy @ HH:mm tt z');

I get the result as
`` Dec 23, 2018 @ 08:00 America/Los_Angeles``

How can I formatted to the following:
``Dec 23, 2018 @ 08:00 AM PST`

**Comment by pepie** [comment]
I was able to solve this through the zoneinterval;

var _zoneName = startDate.inZone(this.timeZone).getZoneInterval().name;

**Comment by Dana-Ferguson** [comment]
You can grab the abbreviation like that, because it actually belongs to the zone interval, and not the timezone. they show that visually here: https://www.timeanddate.com/time/zone/usa/los-angeles 

As far as your question, you can use the `t` and `x` formatters to get am/pm and abbreviation information.
see: https://github.com/Dana-Ferguson/time_machine/blob/master/lib/src/text/zoneddatetime_pattern_parser.dart#L51

**Comment by Dana-Ferguson** [comment]
This, `print(now.inLocalZone().toString('MMM dd, yyyy @ HH:mm tt x'));` got me this `Dec 27, 2018 @ 20:07 PM EST`

**Comment by Dana-Ferguson** [comment]
Something is wrong with the example you posted, since `tt` will not give the timezone printed out.
