### ISSUE TITLE
LocalDate methods name

### ISSUE THREAD

**Issue by Solido** [Dana-Ferguson/time_machine#3]
minusPeriod(Period) -> plus(Period)
minusDate -> no plus
plusDays, etc -> no minus 

Is there a reason for those non symmetric names ?

**Comment by Dana-Ferguson** [comment]
Nope, I have a todo item to look at parallel construction. But in C# (the language of the original library) you can use method overloading, so a lot of these methods were me just throwing a more specific name down so I can get the port going.

My original number 1 priority -- was full port -- full unit tests passing. I was pushing off polish later, which I'm currently working on now (recently, I've been formatting a lot of the public API documentation).

**Comment by Dana-Ferguson** [comment]
Now that I've thought about this a bit harder.

`minusDate` comes from `date - date = period of time`
`minusPeriod` is the `date - period of time = date` concept. When it comes to subtraction it's intuitive to think of subtracting dates to get periods, and subtracting periods to get dates.

`plus(Period)` is the `date + period of time = date` concept.
There is no `plusDate` because `date + date = ????` isn't an intuitive concept.

_Open Question_: `plus(Period)` maybe should be `plusPeriod` to fit in with the `minusDate` and `minusPeriod`?

 * plusDays
 * plusMonths
 * plusWeeks
 * plusYears

These are like this in the [NodaTime](https://nodatime.org/2.2.x/api/NodaTime.LocalDate.html#methods). These methods are convenience methods that do the same as `plus(Period)` and can all be used with negative numbers.

```dart
    var ld = LocalDate.today();

    // These are the same
    ld = ld.plus(Period(years: 1));
    ld = ld.plusYears(1);

    // These are also the same
    ld = ld.plus(Period(years: -1));
    ld = ld.plusYears(-1);
```
One possibility is since Dart 2 has a more declarative format, we could forgo the convenience methods for directly using `Period`'s.

**Comment by Dana-Ferguson** [comment]
```dart
    // (1) Most Flexible
    ld = ld.plus(Period(years: 1));

    // (2) Cheaper
    ld = ld.plusYears(1);
```
Method 1 Does These Things

 * Constructs a Period
 * Two Precondition Checks
    * Verifies Period isn't null
    * Verifies Period is Date-Specific
  * Calls plusYears, plusMonths, plusWeeks, and plusDays
    * Calling these methods with a `0` returns instantly

Method 2 immediately jumps to the end and is more efficient, but less powerful.

**Comment by Dana-Ferguson** [comment]
Continuing to mentally process this, I think it would be wise to look at what already exists in `dart:core.DateTime`.

**Comment by Dana-Ferguson** [comment]
What, I'm thinking to correct the situation.

### core:DateTime API
(for reference)

```dart
DateTime subtract(Duration duration);
bool isAfter(DateTime other);
bool isBefore(DateTime other);
Duration difference(DateTime other);
DateTime add(Duration duration);
```

### LocalDate

old | new
--|--
plus(Period) | add
minusDate | difference
minusPeriod	| subtract

old | new
--|--
plusDays    | addDays + subtractDays
plusMonths | addMonths + subtractMonths
plusWeeks | addWeeks + subtractWeeks
plusYears | addYears + subtractYears

### LocalDate Static
	add(LocalDate date, Period period) -> LocalDate
		--> plus
	between(LocalDate end, LocalDate start) -> Period
		--> differenceBetween // unsure about this one
	subtract(LocalDate, Period) -> LocalDate
	max
	min

**Comment by Solido** [comment]
This is a good solution for method name normalisation,
it makes the code much more readable. Thanks !

**Comment by Dana-Ferguson** [comment]
:) Cool!
I will be implementing these changes after work today. I will also need to look at other classes as well to make sure that they conform to this naming standard,

**Comment by Dana-Ferguson** [comment]
[time_machine 0.9](https://pub.dartlang.org/packages/time_machine) is out, which addresses the above issues.

I still need to produce a hard chart to check for parallel construction across all the classes. (_That's a v1 blocking TBD_);

I will be looking at `difference`, and `until` and `since` methods. 
```dart
// From ZonedDateTime
Time timeSince(ZonedDateTime other);
Time timeUntil(ZonedDateTime other);

// From LocalDateTime (like Duration)
// I think this is the same as `timeSince` but for Periods
Period difference(LocalDateTime localDateTime);
```

**Comment by Solido** [comment]
Hi @Dana-Ferguson  
I moved to the new api and it's feel much more natural.
Thank you !

**Comment by Dana-Ferguson** [comment]
Nope, should I? I don't do much social media.

**Comment by Solido** [comment]
No better stay away ;)
I'm showcasing an app and send some references to libs that I use.
Why didn't you called this project Dota Time (Joda, Noda, Dota) ?

**Comment by Dana-Ferguson** [comment]
Oh yeah, I got that same question from the Noda Time guys, :)
[Doda](https://en.wikipedia.org/wiki/Doda) is a real place, and this is [Doda's Time](https://time.is/Doda)

And now that I'm looking at it, [Joda](https://time.is/Joda) and [Noda](https://time.is/Noda) are real places too. So... barring that defense, Doda is way too close to [Dota](https://www.google.com/search?q=dota), which is a very popular game -- I can see the confusion as problematic -- case in point: see your comment :).

Barring that as a defense, I like whimsical names.

**Comment by Solido** [comment]
I see the Picasso's clock and then Dada Time, I had to tell you how I think of your lib now ;)

**Comment by Solido** [comment]
LocalDate.today and LocalDate.dateTime respond to my last questions.
I close this one, thx.

**Comment by Dana-Ferguson** [comment]
I think I'm nearing the end of getting the public API figured out (lots o' changes went out last night). After that is 'done-ish', I'm gonna open an issue for an API RFC (probably leave it open for a month). Following that, we should be at the v1.0 API.
